# Generated by Django 5.1 on 2024-08-14 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_band_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='band',
            options={'verbose_name': 'Музыкальная группа', 'verbose_name_plural': 'Музыкальные группы'},
        ),
        migrations.AlterField(
            model_name='band',
            name='city',
            field=models.CharField(max_length=50, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='band',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/photos/bands/%Y/%m/%d/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='band',
            name='leader',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='band_leader', to='users.user', verbose_name='Лидер'),
        ),
        migrations.AlterField(
            model_name='band',
            name='members',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='band_members', to='users.user', verbose_name='Участники'),
        ),
        migrations.AlterField(
            model_name='band',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/photos/users/%Y/%m/%d/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('musician', 'Nusician'), ('band', 'Band'), ('organizer', 'Organizer')], default='musician', max_length=50, verbose_name='Роль'),
        ),
    ]
