# Generated by Django 5.1 on 2024-08-23 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_favoritevacancy'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FavoriteVacancy',
        ),
    ]
