# Generated by Django 5.1 on 2024-08-14 20:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_band_options_alter_band_city_alter_band_image_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='band',
            name='leader',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='band_leader', to=settings.AUTH_USER_MODEL, verbose_name='Лидер'),
        ),
        migrations.AlterField(
            model_name='band',
            name='members',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='band_members', to=settings.AUTH_USER_MODEL, verbose_name='Участники'),
        ),
    ]
