# Generated by Django 5.1 on 2024-08-16 14:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_band_leader_alter_band_members'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='band',
            name='members',
        ),
        migrations.AddField(
            model_name='band',
            name='members',
            field=models.ManyToManyField(related_name='band_members', to=settings.AUTH_USER_MODEL, verbose_name='Участники'),
        ),
    ]
