
services:
  app:
    build: .
    command: >
      sh -c "python3 manage.py migrate &&
             python3 manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
  db:
    image: postgres:16-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    container_name: postgres

  redis:
    image: redis:alpine
    container_name: redis
    env_file:
      - .env

  celery:
    restart: always
    build:
      context: .
    command: celery -A config worker -l INFO
    volumes:
      - .:/app
    container_name: celery
    user: "1000:1000"
    depends_on:
      - db
      - redis
      - app
  celery-beat:
    container_name: celery-beat
    build:
      context: .
    command: celery -A config beat -l INFO --scheduler django_celery_beat.schedulers:DatabaseScheduler
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
      - app
  flower:
    container_name: flower
    ports:
      - "5555:5555"
    build:
      context: .
    command: celery -A config flower
    volumes:
      - .:/app
    depends_on:
      - celery

volumes:
  postgres_data:
