openapi: 3.0.3
info:
  title: FindYourBand API
  version: 1.0.0
paths:
  /api/v1/bands/:
    get:
      operationId: v1_bands_retrieve
      tags:
      - v1
      security:
      - cookieAuth: []
      - basicAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Band'
          description: ''
    post:
      operationId: v1_bands_create
      tags:
      - v1
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Band'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Band'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Band'
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Band'
          description: ''
    patch:
      operationId: v1_bands_partial_update
      tags:
      - v1
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchedBand'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PatchedBand'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PatchedBand'
      security:
      - cookieAuth: []
      - basicAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Band'
          description: ''
    delete:
      operationId: v1_bands_destroy
      tags:
      - v1
      security:
      - cookieAuth: []
      - basicAuth: []
      responses:
        '204':
          description: No response body
  /api/v1/news/:
    get:
      operationId: v1_news_retrieve
      tags:
      - v1
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
  /api/v1/news/{slug}/:
    get:
      operationId: v1_news_retrieve_2
      parameters:
      - in: path
        name: slug
        schema:
          type: string
        required: true
      tags:
      - v1
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
  /api/v1/users/favourites/:
    get:
      operationId: v1_users_favourites_list
      tags:
      - v1
      security:
      - cookieAuth: []
      - basicAuth: []
      responses:
        '200':
          description: No response body
    post:
      operationId: v1_users_favourites_create
      tags:
      - v1
      security:
      - cookieAuth: []
      - basicAuth: []
      responses:
        '201':
          description: No response body
  /api/v1/users/favourites/{id}/:
    delete:
      operationId: v1_users_favourites_destroy
      parameters:
      - in: path
        name: id
        schema:
          type: string
        required: true
      tags:
      - v1
      security:
      - cookieAuth: []
      - basicAuth: []
      responses:
        '204':
          description: No response body
  /api/v1/users/profile/:
    get:
      operationId: v1_users_profile_retrieve
      tags:
      - v1
      security:
      - cookieAuth: []
      - basicAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserProfile'
          description: ''
    patch:
      operationId: v1_users_profile_partial_update
      tags:
      - v1
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchedUserProfile'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PatchedUserProfile'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PatchedUserProfile'
      security:
      - cookieAuth: []
      - basicAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserProfile'
          description: ''
  /api/v1/users/vacancies/:
    get:
      operationId: v1_users_vacancies_list
      tags:
      - v1
      security:
      - cookieAuth: []
      - basicAuth: []
      responses:
        '200':
          description: No response body
  /api/v1/users/vacancies/{uuid}/:
    get:
      operationId: v1_users_vacancies_retrieve
      parameters:
      - in: path
        name: uuid
        schema:
          type: string
        required: true
      tags:
      - v1
      security:
      - cookieAuth: []
      - basicAuth: []
      responses:
        '200':
          description: No response body
    put:
      operationId: v1_users_vacancies_update
      parameters:
      - in: path
        name: uuid
        schema:
          type: string
        required: true
      tags:
      - v1
      security:
      - cookieAuth: []
      - basicAuth: []
      responses:
        '200':
          description: No response body
    patch:
      operationId: v1_users_vacancies_partial_update
      parameters:
      - in: path
        name: uuid
        schema:
          type: string
        required: true
      tags:
      - v1
      security:
      - cookieAuth: []
      - basicAuth: []
      responses:
        '200':
          description: No response body
    delete:
      operationId: v1_users_vacancies_destroy
      parameters:
      - in: path
        name: uuid
        schema:
          type: string
        required: true
      tags:
      - v1
      security:
      - cookieAuth: []
      - basicAuth: []
      responses:
        '204':
          description: No response body
  /api/v1/vacancies/:
    get:
      operationId: v1_vacancies_list
      tags:
      - v1
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
    post:
      operationId: v1_vacancies_create
      tags:
      - v1
      security:
      - cookieAuth: []
      - basicAuth: []
      responses:
        '201':
          description: No response body
  /api/v1/vacancies/{uuid}/:
    get:
      operationId: v1_vacancies_retrieve
      parameters:
      - in: path
        name: uuid
        schema:
          type: string
        required: true
      tags:
      - v1
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
components:
  schemas:
    Band:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        name:
          type: string
          title: Название
          maxLength: 50
        city:
          type: string
          title: Город
          maxLength: 50
        image:
          type: string
          format: uri
          nullable: true
          title: Фото
        leader:
          type: integer
          title: Лидер
        members:
          type: array
          items:
            type: integer
            title: Участники
          title: Участники
      required:
      - city
      - id
      - leader
      - members
      - name
    PatchedBand:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        name:
          type: string
          title: Название
          maxLength: 50
        city:
          type: string
          title: Город
          maxLength: 50
        image:
          type: string
          format: uri
          nullable: true
          title: Фото
        leader:
          type: integer
          title: Лидер
        members:
          type: array
          items:
            type: integer
            title: Участники
          title: Участники
    PatchedUserProfile:
      type: object
      properties:
        username:
          type: string
          title: Имя пользователя
          description: Обязательное поле. Не более 150 символов. Только буквы, цифры
            и символы @/./+/-/_.
          pattern: ^[\w.@+-]+$
          maxLength: 150
        first_name:
          type: string
          title: Имя
          maxLength: 150
        last_name:
          type: string
          title: Фамилия
          maxLength: 150
        last_login:
          type: string
          format: date-time
          nullable: true
          title: Последний вход
        email:
          type: string
          format: email
          readOnly: true
          title: Электронная почта
        image:
          type: string
          format: uri
          nullable: true
          title: Фото
    UserProfile:
      type: object
      properties:
        username:
          type: string
          title: Имя пользователя
          description: Обязательное поле. Не более 150 символов. Только буквы, цифры
            и символы @/./+/-/_.
          pattern: ^[\w.@+-]+$
          maxLength: 150
        first_name:
          type: string
          title: Имя
          maxLength: 150
        last_name:
          type: string
          title: Фамилия
          maxLength: 150
        last_login:
          type: string
          format: date-time
          nullable: true
          title: Последний вход
        email:
          type: string
          format: email
          readOnly: true
          title: Электронная почта
        image:
          type: string
          format: uri
          nullable: true
          title: Фото
      required:
      - email
      - username
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
    cookieAuth:
      type: apiKey
      in: cookie
      name: sessionid
