# Generated by Django 5.1 on 2024-08-21 15:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Band',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название')),
                ('city', models.CharField(max_length=50, verbose_name='Город')),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/photos/bands/%Y/%m/%d/', verbose_name='Фото')),
                ('leader', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='band_leader', to=settings.AUTH_USER_MODEL, verbose_name='Лидер')),
                ('members', models.ManyToManyField(related_name='band_members', to=settings.AUTH_USER_MODEL, verbose_name='Участники')),
            ],
            options={
                'verbose_name': 'Музыкальная группа',
                'verbose_name_plural': 'Музыкальные группы',
            },
        ),
    ]
