# Generated by Django 5.1.1 on 2024-09-18 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Band',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Название')),
                ('city', models.CharField(max_length=50, verbose_name='Город')),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/photos/bands/%Y/%m/%d/', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Музыкальная группа',
                'verbose_name_plural': 'Музыкальные группы',
            },
        ),
    ]
