# Generated by Django 5.1 on 2024-08-14 14:26

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BandVacancy',
            fields=[
                ('description', models.TextField(max_length=1000)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('genre', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('rock', 'Rock'), ('pop', 'Pop'), ('jazz', 'Jazz'), ('classical', 'Classical'), ('metal', 'Metal'), ('electronic', 'Electronic'), ('other', 'Other')], max_length=50), size=3)),
                ('level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('contacts', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), size=3)),
                ('instrument', models.CharField(choices=[('guitar', 'Guitar'), ('bass', 'Bass'), ('drums', 'Drums'), ('piano', 'Piano'), ('other', 'Other')], max_length=50)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MusicianVacancy',
            fields=[
                ('description', models.TextField(max_length=1000)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('genre', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('rock', 'Rock'), ('pop', 'Pop'), ('jazz', 'Jazz'), ('classical', 'Classical'), ('metal', 'Metal'), ('electronic', 'Electronic'), ('other', 'Other')], max_length=50), size=3)),
                ('level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('contacts', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), size=3)),
                ('instruments', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('guitar', 'Guitar'), ('bass', 'Bass'), ('drums', 'Drums'), ('piano', 'Piano'), ('other', 'Other')], max_length=50), size=3)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrganizerVacancy',
            fields=[
                ('description', models.TextField(max_length=1000)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('event_type', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('event_datetime', models.DateTimeField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
