# Generated by Django 5.1.1 on 2024-09-18 17:17

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bands', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BandVacancy',
            fields=[
                ('description', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Описание')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=50, verbose_name='Уровень игры')),
                ('city', models.CharField(max_length=50, verbose_name='Город')),
                ('contacts', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), size=3, verbose_name='Контакты')),
                ('instrument', models.CharField(choices=[('guitar', 'Guitar'), ('bass', 'Bass'), ('drums', 'Drums'), ('piano', 'Piano'), ('other', 'Other')], max_length=50, verbose_name='Инструмент')),
                ('genres', models.CharField(choices=[('rock', 'Rock'), ('pop', 'Pop'), ('jazz', 'Jazz'), ('classical', 'Classical'), ('metal', 'Metal'), ('electronic', 'Electronic'), ('other', 'Other')], max_length=50, verbose_name='Жанр')),
                ('created_by', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='band_vacancy', to='bands.band', verbose_name='Группа')),
                ('favourites', models.ManyToManyField(blank=True, related_name='%(class)s_favourites', to=settings.AUTH_USER_MODEL, verbose_name='Избранное')),
            ],
            options={
                'verbose_name': 'Объявление группы',
                'verbose_name_plural': 'Объявления групп',
            },
        ),
        migrations.CreateModel(
            name='MusicianVacancy',
            fields=[
                ('description', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Описание')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('genres', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('rock', 'Rock'), ('pop', 'Pop'), ('jazz', 'Jazz'), ('classical', 'Classical'), ('metal', 'Metal'), ('electronic', 'Electronic'), ('other', 'Other')], max_length=50), default=list, size=3, verbose_name='Жанры')),
                ('level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=50, verbose_name='Уровень игры')),
                ('city', models.CharField(max_length=50, verbose_name='Город')),
                ('contacts', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), size=3, verbose_name='Контакты')),
                ('instruments', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('guitar', 'Guitar'), ('bass', 'Bass'), ('drums', 'Drums'), ('piano', 'Piano'), ('other', 'Other')], max_length=50), default=list, size=3, verbose_name='Инструменты')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('favourites', models.ManyToManyField(blank=True, related_name='%(class)s_favourites', to=settings.AUTH_USER_MODEL, verbose_name='Избранное')),
            ],
            options={
                'verbose_name': 'Объявление музыканта',
                'verbose_name_plural': 'Объявления музыкантов',
            },
        ),
        migrations.CreateModel(
            name='OrganizerVacancy',
            fields=[
                ('description', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Описание')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('event_type', models.CharField(max_length=255, verbose_name='Тип мероприятия')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес мероприятия')),
                ('event_datetime', models.DateTimeField(verbose_name='Время мероприятия')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('favourites', models.ManyToManyField(blank=True, related_name='%(class)s_favourites', to=settings.AUTH_USER_MODEL, verbose_name='Избранное')),
            ],
            options={
                'verbose_name': 'Объявление организатора',
                'verbose_name_plural': 'Объявления организаторов',
            },
        ),
    ]
