# Generated by Django 5.1 on 2024-08-21 17:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organizervacancy',
            options={'verbose_name': 'Объявление организатора', 'verbose_name_plural': 'Объявления организаторов'},
        ),
        migrations.AddField(
            model_name='bandvacancy',
            name='favourites',
            field=models.ManyToManyField(blank=True, related_name='%(class)s_favourites', to=settings.AUTH_USER_MODEL, verbose_name='Избранное'),
        ),
        migrations.AddField(
            model_name='musicianvacancy',
            name='favourites',
            field=models.ManyToManyField(blank=True, related_name='%(class)s_favourites', to=settings.AUTH_USER_MODEL, verbose_name='Избранное'),
        ),
        migrations.AddField(
            model_name='organizervacancy',
            name='favourites',
            field=models.ManyToManyField(blank=True, related_name='%(class)s_favourites', to=settings.AUTH_USER_MODEL, verbose_name='Избранное'),
        ),
    ]
