# Generated by Django 5.1 on 2024-08-14 14:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bandvacancy',
            options={'verbose_name': 'Объявления групп', 'verbose_name_plural': 'Объявления групп'},
        ),
        migrations.AlterModelOptions(
            name='musicianvacancy',
            options={'verbose_name': 'Объявления музыкантов', 'verbose_name_plural': 'Объявления музыкантов'},
        ),
        migrations.AlterModelOptions(
            name='organizervacancy',
            options={'verbose_name': 'Объявления организоторов', 'verbose_name_plural': 'Объявления организоторов'},
        ),
        migrations.AlterField(
            model_name='bandvacancy',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='musicianvacancy',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='organizervacancy',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
