# Generated by Django 5.1 on 2024-08-23 15:19

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0002_alter_organizervacancy_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bandvacancy',
            name='genres',
            field=models.CharField(choices=[('rock', 'Rock'), ('pop', 'Pop'), ('jazz', 'Jazz'), ('classical', 'Classical'), ('metal', 'Metal'), ('electronic', 'Electronic'), ('other', 'Other')], max_length=50, verbose_name='Жанр'),
        ),
        migrations.AlterField(
            model_name='musicianvacancy',
            name='genres',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('rock', 'Rock'), ('pop', 'Pop'), ('jazz', 'Jazz'), ('classical', 'Classical'), ('metal', 'Metal'), ('electronic', 'Electronic'), ('other', 'Other')], max_length=50), default=list, size=3, verbose_name='Жанры'),
        ),
    ]
