# Generated by Django 5.1 on 2024-08-14 19:34

import vacancies.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0002_alter_bandvacancy_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bandvacancy',
            options={'verbose_name': 'Объявление группы', 'verbose_name_plural': 'Объявления групп'},
        ),
        migrations.AlterModelOptions(
            name='musicianvacancy',
            options={'verbose_name': 'Объявление музыканта', 'verbose_name_plural': 'Объявления музыкантов'},
        ),
        migrations.AlterModelOptions(
            name='organizervacancy',
            options={'verbose_name': 'Объявление организотора', 'verbose_name_plural': 'Объявления организоторов'},
        ),
        migrations.AlterField(
            model_name='bandvacancy',
            name='city',
            field=models.CharField(max_length=50, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='bandvacancy',
            name='level',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=50, verbose_name='Уровень игры'),
        ),
        migrations.AlterField(
            model_name='musicianvacancy',
            name='city',
            field=models.CharField(max_length=50, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='musicianvacancy',
            name='instruments',
            field=vacancies.utils.ChoiceArrayField(base_field=models.CharField(max_length=50), choices=[('guitar', 'Guitar'), ('bass', 'Bass'), ('drums', 'Drums'), ('piano', 'Piano'), ('other', 'Other')], size=3),
        ),
        migrations.AlterField(
            model_name='musicianvacancy',
            name='level',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=50, verbose_name='Уровень игры'),
        ),
    ]
