# Generated by Django 5.1 on 2024-08-14 21:25

import vacancies.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0005_alter_bandvacancy_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bandvacancy',
            name='genre',
            field=vacancies.utils.ChoiceArrayField(base_field=models.CharField(max_length=50), choices=[('Rock', 'Rock'), ('Pop', 'Pop'), ('jazz', 'Jazz'), ('classical', 'Classical'), ('metal', 'Metal'), ('electronic', 'Electronic'), ('other', 'Other')], size=3, verbose_name='Жанр'),
        ),
        migrations.AlterField(
            model_name='musicianvacancy',
            name='genre',
            field=vacancies.utils.ChoiceArrayField(base_field=models.CharField(max_length=50), choices=[('Rock', 'Rock'), ('Pop', 'Pop'), ('jazz', 'Jazz'), ('classical', 'Classical'), ('metal', 'Metal'), ('electronic', 'Electronic'), ('other', 'Other')], size=3, verbose_name='Жанр'),
        ),
    ]
