# Generated by Django 5.1 on 2024-08-14 21:35

import vacancies.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0006_alter_bandvacancy_genre_alter_musicianvacancy_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musicianvacancy',
            name='instruments',
            field=vacancies.utils.ChoiceArrayField(base_field=models.CharField(max_length=50), choices=[('guitar', 'Guitar'), ('bass', 'Bass'), ('drums', 'Drums'), ('piano', 'Piano'), ('other', 'Other')], default='other', size=3, verbose_name='Инструменты'),
        ),
    ]
