# Generated by Django 5.1 on 2024-08-14 21:40

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0007_alter_musicianvacancy_instruments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musicianvacancy',
            name='instruments',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('guitar', 'Guitar'), ('bass', 'Bass'), ('drums', 'Drums'), ('piano', 'Piano'), ('other', 'Other')], max_length=50), default=list, size=3, verbose_name='Инструменты'),
        ),
    ]
