# Generated by Django 5.1 on 2024-08-14 21:43

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0008_alter_musicianvacancy_instruments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bandvacancy',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='musicianvacancy',
            name='genre',
        ),
        migrations.AddField(
            model_name='bandvacancy',
            name='genres',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('rock', 'Rock'), ('pop', 'Pop'), ('jazz', 'Jazz'), ('classical', 'Classical'), ('metal', 'Metal'), ('electronic', 'Electronic'), ('other', 'Other')], max_length=50), default=list, size=3, verbose_name='Жанр'),
        ),
        migrations.AddField(
            model_name='musicianvacancy',
            name='genres',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('rock', 'Rock'), ('pop', 'Pop'), ('jazz', 'Jazz'), ('classical', 'Classical'), ('metal', 'Metal'), ('electronic', 'Electronic'), ('other', 'Other')], max_length=50), default=list, size=3, verbose_name='Жанр'),
        ),
    ]
