# Generated by Django 5.1 on 2024-08-16 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_band_members_band_members'),
        ('vacancies', '0010_alter_bandvacancy_genres_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bandvacancy',
            name='created_by',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='band_vacancy', to='users.band', verbose_name='Группа'),
        ),
    ]
