# Generated by Django 5.1.1 on 2024-12-26 23:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('MusicianVacancy', 'Вакансии музыкантов'), ('BandVacancy', 'Вакансии групп'), ('OrganizerVacancy', 'Вакансии организаторов'), ('Messages', 'Сообщения'), ('News', 'Новости')], max_length=50, verbose_name='Тип уведомления')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Подписка на уведомления',
                'verbose_name_plural': 'Подписки на уведомления',
                'unique_together': {('user', 'notification_type')},
            },
        ),
    ]
